baseURL = 'https://agiletechies.com/'
languageCode = 'en-us'
title = 'The Agile Techies Daily List'
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

[module]
[[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'

[minify]
disableXML = true

[pagination]
pagerSize = 5

[languages.en]
languageName = "English"
weight = 1

  [languages.en.taxonomies]
  tag = "tags"

[[languages.en.menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[outputs]
home = [ "HTML", "JSON" ]
section = [ "HTML", "RSS" ]

[params]
hideAuthor = true
DateFormat = "2006 January 2"
mainsections = [ "posts" ]
env = "production"
description = "Raj Duggal coaches teams on how to develop and deliver high-quality software with an aim towards maximizing end-user value"
social = true
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = false
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = false
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = false
ShowPageNums = true
ShowToc = false
images = [ "images/papermod-cover.png" ]

  [params.author]
  name = "Raj Duggal"
  email = "rajesh@duggalmail.com"

  [params.profileMode]
  enabled = true
  title = "The Agile Techies Daily List"
  subTitle = """
<p>ðŸ‘‹
  For <u><a href="https://rajduggal.com/articles/but-im-not-a-software-developer/">software builders</a></u> that enjoy delivering high-quality working software.</p>
<p>Yes, it's actually daily. And yes, people actually stay subscribed.</p>
"""
  imageUrl = "/images/main.jpg"

  [[params.profileMode.buttons]]
  name = "Not sure? Browse the archive >>"
  url = "archives"

  [params.homeInfoParams]
  Title = "The Agile Techies Daily List"
  Content = """
ðŸ‘‹
  For software builders who want to know how to deliver high-quality working software with a smile instead of a headache"
- Yes, its actually daily. And yes, people actually stay subscribed.
- (Add convertkit form here)
"""

  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[services.instagram]
disableInlineCSS = true

[services.x]
disableInlineCSS = true

[services.googleAnalytics]
id = "G-VJVLBYZ7XM"
